# backend/api/urls.py

from django.urls import path, include
from rest_framework.routers import SimpleRouter
from rest_framework_nested.routers import NestedSimpleRouter
from .views import (
    RegisterView, 
    VerifyOTPView,
    LoginView, 
    LogoutView, 
    ProfileView, 
    DeleteUserView,
    PasswordResetRequestView, 
    PasswordResetConfirmView,
    CompleteProfileView,
    PostViewSet,
    CommentViewSet,
    ProfileDetailView,
    FollowListView,
    InterestedPostsView,
    RecruiterPostsView,
    FollowingListView
)
from .views import FollowToggleView, FollowStatsView
from .views import UserListView 
from .views import MessageHistoryView # 1. Import the view
from .views import UserSearchView # Add this import
from .views import SkillListView, UserSkillView # Add these imports


# Create a router and register our viewsets with it.
router = SimpleRouter()
router.register(r'posts', PostViewSet, basename='post')

posts_router = NestedSimpleRouter(router, r'posts', lookup='post')
posts_router.register(r'comments', CommentViewSet, basename='post-comment')

# The API URLs are now determined automatically by the router.
urlpatterns = [
    # This line includes all the URLs generated by the router (e.g., /api/posts/)
    path('', include(router.urls)),
    path('', include(posts_router.urls)),

    # Your other, non-router URLs
    path('register/', RegisterView.as_view(), name='register'),
    path('verify-otp/', VerifyOTPView.as_view(), name='verify-otp'),
    path('complete-profile/', CompleteProfileView.as_view(), name='complete-profile'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/delete/', DeleteUserView.as_view(), name='delete-user'),
    path('password-reset/request/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('profiles/<str:username>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('users/<int:user_id>/follow/', FollowToggleView.as_view(), name='follow-toggle'),
    path('users/<int:user_id>/follow-stats/', FollowStatsView.as_view(), name='follow-stats'),
    path('users/<int:user_id>/followers/', FollowListView.as_view(), {'list_type': 'followers'}, name='follower-list'),
    path('users/<int:user_id>/following/', FollowListView.as_view(), {'list_type': 'following'}, name='following-list'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('chat/history/<int:user_id>/', MessageHistoryView.as_view(), name='message-history'),
    path('interested-posts/', InterestedPostsView.as_view(), name='interested-posts'),
    path('recruiter-posts/', RecruiterPostsView.as_view(), name='recruiter-posts'),
    path('search/users/', UserSearchView.as_view(), name='user-search'),
    path('skills/', SkillListView.as_view(), name='skill-list'),
    path('profile/skills/<int:skill_id>/', UserSkillView.as_view(), name='user-skill-toggle'),
    path('following/', FollowingListView.as_view(), name='following-list'),



]